whatwg/whatwg.org

src/status-2008-12
=> Add a disclaimer to status-2008-12

src/.htaccess, src/demos/.htaccess
Fixes part of https://github.com/whatwg/html/issues/2620.
=> Correct /demos/workers/ redirect

src/specs/index, src/validator/index.html
Per discussion in #31. Also fix #32.
=> Restore html5.validator.nu

src/404, src/charter, src/code-of-conduct, src/mailing-list, src/news/index, src/specs/index, src/validator/index.html, src/working-mode
=> Move the Code of Conduct here

src/validator/index.html
validator.whatwg.org redirects to whatwg.org/validator/
=> Remove incorrect comment

images.whatwg.org/.htaccess, n.whatwg.org/.htaccess
The config will be elsewhere:
https://github.com/whatwg/misc-server/commit/c61552ac840b1fb99031a9252945da287cf66180
=> Remove .htaccess for images.whatwg.org and n.whatwg.org

resources.whatwg.org/build/deploy.sh
See https://github.com/whatwg/whatwg.org/issues/65#issuecomment-325331716.
=> Update link to standard-service-worker.js after repo merge

spec.whatwg.org/index.html
And a bonus commit for re-wrapping
=> Update Streams Standard description

resources.whatwg.org/build/deploy.sh
Fixes https://github.com/whatwg/whatwg.org/issues/73.
=> Simplify and delay standard-service-worker.js sha calculation

whatwg.org/specs/web-controls/current-work/index
=> Add banner to web-controls

.travis.yml, deploy.sh, resources.whatwg.org/build/deploy.sh
=> Run shellcheck

resources.whatwg.org/build/deploy.sh
Usage example for encoding, in .travis.yml:
```
- POST_BUILD_STEP="python visualize.py \"$DIR/\""
```
Part of https://github.com/whatwg/meta/issues/11.
=> deploy.sh: support running a post build step

resources.whatwg.org/build/README.md
Documentation for:
* https://github.com/whatwg/whatwg.org/pull/68
* https://github.com/whatwg/whatwg.org/pull/81
* https://github.com/whatwg/whatwg.org/pull/82
=> deploy.sh: document optional environment variables like EXTRA_FILES

resources.whatwg.org/biblio.json
See https://github.com/tobie/specref/issues/382.
=> Update URLs of Books and Figures in biblio.json

resources.whatwg.org/biblio.json
See https://github.com/whatwg/streams/commit/f1ecc04aa3836e3933f2089b97992dac33c3bc34
and https://github.com/whatwg/console/commit/4491335af4bd38c44dd576819292e63cba0f0d8f.
=> Add some editors for Console and Streams

whatwg.org/.htaccess
Only 404 and 410 actually exist.
=> Remove some broken ErrorDocument lines in .htaccess

spec.whatwg.org/index.html
Fixes https://github.com/whatwg/whatwg.org/issues/102.
=> Use alphabetical order on spec.whatwg.org

whatwg.org/.htaccess
What remains is all that's still relevant, no files of the other patterns exist.
=> Simplify .htaccess IndexIgnore/DirectoryIndex

resources.whatwg.org/build/deploy.sh
Part of https://github.com/whatwg/misc-server/issues/7.
=> Stop deploying to the old server

.travis.yml, deploy.sh, resources.whatwg.org/build/README.md
Also clean up README.md to match changes in https://github.com/whatwg/whatwg.org/pull/119.
=> Remove another bit of old deploy server

idea.whatwg.org/index.html, spec.whatwg.org/index.html, whatwg.org/404, whatwg.org/charter, whatwg.org/code-of-conduct, whatwg.org/demos/2008-sept/index.html, whatwg.org/demos/index.html, whatwg.org/faq, whatwg.org/index.html, whatwg.org/ipr-policy, whatwg.org/mailing-list, whatwg.org/news/future-of-html, whatwg.org/news/index.html, whatwg.org/news/start, whatwg.org/news/web-forms-call-for-comments-1, whatwg.org/news/web-forms-call-for-comments-2, whatwg.org/news/web-forms-call-for-comments-3, whatwg.org/news/web-forms-call-for-comments-4, whatwg.org/policies, whatwg.org/principles, whatwg.org/sg-agreement, whatwg.org/sg-policy, whatwg.org/style/tabbed-pages, whatwg.org/validator/index.html, whatwg.org/working-mode, whatwg.org/workstream-policy
https://blog.whatwg.org/working-mode-changes
=> Publish updates for working mode changes

whatwg.org/policies
Reverts whatwg/whatwg.org#129.
=> Editorial: remove incorrectly added "The"

resources.whatwg.org/build/deploy.sh
See https://github.com/whatwg/whatwg.org/pull/135#issuecomment-352470978
=> deploy.sh: only list files in $WEB_ROOT when we put something there

resources.whatwg.org/build/deploy.sh
Matches https://github.com/whatwg/html-build/pull/138
=> deploy.sh: document what --chmod=D755,F644 means

resources.whatwg.org/build/README.md
See https://github.com/whatwg/whatwg.org/pull/137.
=> Document the use of "branches: only: master" in .travis.yml files

README.md, whatwg.org/code-of-conduct
Upstreams https://github.com/whatwg/sg/pull/52 manually and adjusts the README.
=> Editorial: use Oxford comma in Code of Conduct

resources.whatwg.org/logo-quirks.svg
See https://github.com/whatwg/quirks/pull/20 for motivation.
=> Add logo-quirks.svg to resources.whatwg.org

resources.whatwg.org/standard.css
=> Change domintro box labels to be more explicit (and not slanted)

resources.whatwg.org/build/deploy.sh
=> Improve context in deploy.sh

n.whatwg.org/formdata, n.whatwg.org/work
=> Update n.whatwg.org namespace documents

resources.whatwg.org/build/deploy.sh
Fixes https://github.com/whatwg/meta/issues/32.
=> Make standards deploy a robots.txt resource too

whatwg.org/index.html
As pointed out in IRC by @tabatkins and a-ja.
=> Change the homepage link to the HTML Standard to go to multipage

resources.whatwg.org/build/deploy.sh
Also add even more context and improve the context added in a prior commit somewhat.
Helps with #117.
=> Check for Bikeshed errors and warnings during deploy

whatwg.org/mailing-list
Also inline the remaining mailing list FAQ entries from the wiki.
Fixes #51.
=> Advise people to use GitHub over the mailing list

resources.whatwg.org/build/deploy.sh
In particular, make "headers" stand out more.
=> Further improvements to standard build logs

resources.whatwg.org/nginx-fancyindex-whatwg.css
Relates to https://github.com/whatwg/whatwg.org/issues/91 and https://github.com/whatwg/misc-server/pull/79
=> Add WHATWG-themed CSS for nginx directory listings

resources.whatwg.org/biblio.json
Matches https://github.com/whatwg/sg/pull/60.
=> Update Fullscreen "authors" in biblio.json

resources.whatwg.org/build/deploy.sh
Closes #163. Also fixes some stylistic issues identified by shellcheck. (They were not breaking the build since they were just stylistic, it appears.)
Tested locally with a few specs.
=> Shared deploy: include extra files in the service worker

.gitignore, deploy.sh
Per discussions in https://github.com/tabatkins/bikeshed/pull/1239/files#r187543719 we want grayed-out logos for review drafts and other snapshots.
=> Generate snapshot logo SVGs

resources.whatwg.org/standard.css
See https://github.com/whatwg/html-build/pull/162
=> Add syntax-highlighter styles

whatwg.org/irc
Escaped angle brackets on irc example on irc file for whatwg.org site; closes #212
=> Escaped angle brackets on irc example on irc file for whatwg.org site; closes #212

whatwg.org/style-guide
Per https://github.com/whatwg/html/pull/2789#discussion_r204320470
=> Add "queuing" as opposed to "queueing"

idea.whatwg.org/index.html, idea.whatwg.org/service-worker.js, resources.whatwg.org/website-service-worker.js, spec.whatwg.org/service-worker.js, whatwg.org/service-worker.js
968af02faaa8eb00673ddbd93411d2895fb772e5 accidentally included some URLs that don't exist in the to-cache list.
Oops.
=> Website service worker fixups

resources.whatwg.org/standard.css
Should also help with performance as per https://github.com/whatwg/whatwg.org/issues/220#issuecomment-412226368.
=> Remove rule redundant with syntax highlighting

resources.whatwg.org/build/deploy.sh
=> Abort deploy when Bikeshed finds a warning

whatwg.org/irc
/cc @annevk 
Fixes: whatwg/meta#108
=> Add registration instructions and suggest +r on IRC (fixes whatwg/meta#108)

resources.whatwg.org/standard-service-worker.js
Closes https://github.com/whatwg/streams/issues/955.
/cc @annevk @ricea @wanderview
=> Set mode: "cors" when precaching standard resources

resources.whatwg.org/standard.css
See https://github.com/whatwg/wattsi/pull/90
=> Add styles for <wpt> output to standard.css

package.json
| Old logo | New Logo |
|:---|:---|
| ![](https://raw.githubusercontent.com/alrra/browser-logos/8fab53c2544fe45642f4b330f21c426a07c63367/src/archive/firefox_57-70/firefox_57-70_512x512.png) | ![](https://raw.githubusercontent.com/alrra/browser-logos/8fab53c2544fe45642f4b330f21c426a07c63367/src/firefox/firefox_512x512.png)
=> Update Firefox logo

README.md
We are no longer on a sponsored plan.
Thanks for the past sponsorship though!
=> Drop DigitalOcean acknowledgment

deploy.sh
See https://github.com/whatwg/whatwg.org/issues/287.
=> Avoid listing files entirely when deploying

deploy.sh
This also adds --stats for minimal logging in the CI log.
Closes #287 hopefully.
=> Add back some rsync logging

deploy.sh
I'm pretty sure this should work.
=> Ensure scp knows the target server as well

deploy.sh
Closes #10.
Unclear whether this will work with all our extension-less files; let's see what Travis does.
=> Conformance check the deployed HTML

convert-policy.py
Closes https://github.com/whatwg/sg/issues/78.
=> Add rel=license back

resources.whatwg.org/build/deploy.sh
Forgotten in cb670f0b02228dbec412f35e6221e564d88f1853.
=> Remove unused variable from build/deploy.sh

resources.whatwg.org/standard-shared-with-dev.css
Relates to https://github.com/whatwg/wattsi/pull/116
=> Adjust placement of MDN annos for table/list items

whatwg.org/style-guide
Follows https://github.com/whatwg/html/pull/5499.
=> Add popup to the Style Guide

resources.whatwg.org/build/deploy.sh
Matches https://github.com/whatwg/whatwg.org/blob/d3bcf77c4ed3591981e3fc4931dcdf4f78fa8ed3/deploy.sh#L68
=> Print "Skipping deploy" to make it obvious

.github/workflows/build.yml
Matches https://github.com/whatwg/spec-factory/pull/16.
=> Rename deploy workflow / job to match specs

resources.whatwg.org/standard-shared-with-dev.css
https://html-mdn.herokuapp.com/output/ can be used to preview the rendered output this change produces.
=> Add styles for caniuse links in MDN annotations

LICENSE, convert_sg_db.py, lists.whatwg.org/index.html, whatwg.org/404, whatwg.org/410, whatwg.org/faq, whatwg.org/index.html, whatwg.org/irc, whatwg.org/style-guide, whatwg.org/validator/index.html
Helps with https://github.com/whatwg/sg/issues/102.
=> Remove year from copyright line

resources.whatwg.org/standard-mdn-annos.js
This change adds an event listener for expanding and un-expanding MDN annos.
Blocks https://github.com/tabatkins/bikeshed/pull/1710
=>     Add script for expanding/un-expanding MDN annos

resources.whatwg.org/build/review.sh
Helps with https://github.com/whatwg/sg/issues/124.
=> review.sh: update LATESTRD field

.github/workflows/build.yml, .gitignore, deploy.sh, resources.whatwg.org/build/README.md, resources.whatwg.org/build/deploy.sh, resources.whatwg.org/build/review.sh, whatwg.org/faq
Helps with https://github.com/whatwg/meta/issues/174.
(I used `grep -r master * --exclude-dir={forums.whatwg.org,lists.whatwg.org}` to identify these. There's also some hits in archived HTML drafts, but I don't thing we should touch those.)
=> Default branch rename

convert_sg_db.py
=> List Twitter accounts on spec.whatwg.org

resources.whatwg.org/build/deploy.sh
See https://github.com/whatwg/html/pull/6570
=> Lint for non-breaking spaces

deploy.sh, resources.whatwg.org/build/deploy.sh
See this monologue for context: https://freenode.logbot.info/whatwg/20210512#c7977887.
=> build.sh: adjust HTML checker download location

whatwg.org/chat
=> No more IRC

whatwg.org/chat
IRC logs moved. Closes https://github.com/whatwg/meta/issues/210.
=> Bye logbot

whatwg.org/service-worker.js
Use v3 as toCache was changed twice thus far.
Fixes remainder of https://github.com/whatwg/meta/issues/217.
=> Add cacheKey to whatwg.org/service-worker.js

package.json
| Old logo | New Logo |
|:---|:---|
| ![](https://user-images.githubusercontent.com/1223565/155402598-8a11a0d2-1e53-4f09-a05f-7c6e47f8fa01.png) | ![](https://user-images.githubusercontent.com/1223565/155402572-d317716f-40c0-4282-92ab-b8cac336ac27.png) |
Ref / See also: https://github.com/alrra/browser-logos/issues/206
=> Update Chrome logo

resources.whatwg.org/build/deploy.sh
This actually uses the .bs file in the review-drafts/ folder, which will have fixed Date: metadata, instead of using the living-standard file. Closes #348.
---
I tested this locally and, in combination with https://github.com/whatwg/meta/pull/254 (which adds `Status: RD` to the source files), it seems to work.
=> Fix deploy.sh to process Review Drafts better

whatwg.org/style-guide
See https://github.com/whatwg/html/pull/9083.
=> Add 'overlaid' to dictionary

resources.whatwg.org/standard.css
This PR fixes a few visible issues in the style sheet. Please see comments below for explanations.
=> Fix a few issues in standard.css

resources.whatwg.org/build/deploy.sh
The CSSWG API is often down, and it's bad for it to block our builds and deploys. The pypi package repository is presumably down less.
This should be rolled out only after https://github.com/whatwg/spec-factory/pull/42 is merged and deployed across repos.
=> Use locally-installed Bikeshed instead of CSSWG API

whatwg.org/style-guide
This is used by ShadowRoot already.
=> Add "clonable" to the dictionary

whatwg.org/style/subpages.css
This is needed for the Stages document.
See https://github.com/whatwg/sg/commit/223c7eb8de16e4664b4f38ce581f0d0744f73236 for more context.
=> Make self-links work inside td elements

whatwg.org/chat
Adds a date the matrix bot had last archived the room.
=> Update dead Matrix archive status

whatwg.org/style-guide
Context: https://github.com/whatwg/html/pull/11035.
=> Add color component to the Style Guide

resources.whatwg.org/standard-service-worker.js, resources.whatwg.org/standard-shared-with-dev.css, resources.whatwg.org/standard.css
While .applies is specific to HTML (for now), it seems best to include that rule here.
=> Align on .yesno styling

convert_policy.py, site-template.html, whatwg.org/service-worker.js
=> Make the Policies page fit in

.github/workflows/build.yml
Align with https://github.com/whatwg/spec-factory/commit/c00f91cff2662f69870f15bb8401d3477b80fea6.
=> Meta: bump GitHub Actions

convert_sg_db.py, whatwg.org/service-worker.js
=> Make the Policies page fit in, part two

resources.whatwg.org/standard-service-worker.js, resources.whatwg.org/standard.css
See https://github.com/whatwg/html/pull/11392#issuecomment-3232396025, 6th bullet.
I changed tabs to 2-spaces, but wasn't sure if WHATWG style wants other changes. Also, I didn't know where to put it, so just stuck it at the end.
=> Update standard.css: Copy in var-click-highlighting.css from bikeshed
