whatwg/whatwg.org

README.md
src/.htaccess
src/404
src/charter
src/index
src/specs/index

* Fixes #11 by adding a README.
* Fixes #14 by redirecting /specs/ to spec.whatwg.org.
* Fixes #15 by using spokesperson and removing the mention of HTML5.
* Fixes #13 by redirecting to whatwg/meta for queries.
* Addresses #9 partly by removing one reference to HTML for developers.
* Fixes #3 by mentioning this repository as the source of (potential)
trouble.

Fix various issues with the site

---

src/404
src/charter
src/index
src/mailing-list

Fixes #9. Also reference checker.html5.org rather than validator.nu as
@sideshowbarker keeps that more up-to-date.

Replace reference to developers.whatwg.org with blog.whatwg.org

---

src/robots.txt

Syntax found at
https://support.archive-it.org/hc/en-us/articles/208001096-Avoid-robots-exclusions.
Fixes #19.

Allow Internet Archive in robots.txt

---

src/robots.txt

See http://webmasters.stackexchange.com/q/71377/11849. Hopefully fixes #19 better.

Try harder to allow archive.org to index old specs

---

src/.htaccess
src/code-of-conduct
src/faq
src/specs/index
src/working-mode

This was produced starting from the HTML output of
https://wiki.whatwg.org/wiki/FAQ and cleaning it up to match the style
of /working-mode and /code-of-conduct. Only very minor visible changes
were made around whitespace, quotes and similar. Actual changes to the
FAQ will be made separately.
Some minimal amount of style is carried over or invented to make it not
much worse than the old FAQ.
All IDs are preserved.

Move the FAQ here

---

src/faq
src/index
src/specs/index

... and link to the HTML FAQ from the WHATWG FAQ, since the main page
points to it and people may be looking for that content.

Update links to wiki/FAQ

---

src/specs/index

See https://github.com/whatwg/books/issues/4, https://github.com/whatwg/figures/issues/3, and https://github.com/whatwg/misc-server/issues/6.
Also remove a pointer to the HTML Standard FAQ as it's not really that useful.
Fix #37 while here.

Move Books and Figures to idea.whatwg.org

---

src/faq

In particular:
* Point out more clearly we're about standards and tests.
* Point to Working Mode.
* Stop pointing to the mailing list.
* Stop using the word "spec".

Improve the FAQ

---

resources.whatwg.org/build/deploy.sh

It's not obvious to look for it in the whatwg.org repo.

Point to the source of the common deploy.sh script

---

resources.whatwg.org/build/README.md
resources.whatwg.org/build/deploy.sh

... with the magic of rsync.
Will be used for https://github.com/whatwg/console/pull/118.

deploy.sh: make EXTRA_FILES preserve directory structure

---

whatwg.org/demos/2008-sept/index

The embed snipped suggested by YouTube is used verbatim.

Replace a YouTube <embed> with <iframe>

---

whatwg.org/demos/2008-sept/index

This matches the videoWidth/videoHeight of the video element after
loading, and means bigger video with no black borders.

Tweak the size of the YouTube <iframe>

---

whatwg.org/.htaccess

https://html.spec.whatwg.org/multipage redirects to https://html.spec.whatwg.org/multipage/

Add trailing slashes to multipage redirects

---

resources.whatwg.org/build/deploy.sh

This is needed for https://github.com/whatwg/encoding/pull/121.

Use --Werror for vnu.jar and pass $CHECKER_FILTER to --filterpattern

---

spec.whatwg.org/index.html

The <strong> appears to be needed.

Fix the styling of https://spec.whatwg.org/

---

whatwg.org/sg-agreement

Should be fixed in the conversion script, of course, later.

Manually fix a few Markdown->HTML conversion errors

---

resources.whatwg.org/build/deploy.sh

These are not useful now that we have PR preview:
https://github.com/whatwg/meta/issues/53
This allows for some simplification of the script too.
Fixes https://github.com/whatwg/meta/issues/52.

Stop deploying branch snapshots

---

resources.whatwg.org/build/deploy.sh

The "Skipping deploy for a pull request" is removed, meaning that the
same steps will be run for both a "branch update" (a branch pushed to
the whatwg/foo repo) and a "pull request update" (a PR opened on the
whatwg/foo repo).
Just PR builds should be enough, and to avoid unnecessary work branch
builds could be limited to master in .travis.yml:
https://docs.travis-ci.com/user/customizing-the-build/#Safelisting-or-blocklisting-branches
There's no reason to check ENCRYPTION_LABEL up front, as the deploy
bits are guarded by being on Travis and master, where the secrets
should always be available.
The commit snapshots will be done on master whether on Travis or not,
so that it can be tested locally more easily.

Simplify deploy.sh to share most of the steps in most cases

---

convert-policy.py
whatwg.org/sg-agreement
whatwg.org/workstream-policy

Fixes #45
Regenerate HTML versions of policy documents with the fixed script.

Fix Markdown conversion script to avoid creating bogus links

---

resources.whatwg.org/standard.css

Before: ![](https://screenshots.firefoxusercontent.com/images/b4eba0a5-dd83-472f-8787-9be8af64a447.png) after: ![](https://screenshots.firefoxusercontent.com/images/a8fbcb85-9fcd-45a0-8040-de389a2d7456.png)

Keep the margin on <p>s inside notes

---

resources.whatwg.org/build/deploy.sh

- We don't use Title: in the source documents anymore, so scrape the H1: instead
- Work around https://github.com/tabatkins/bikeshed/issues/1162

Fix deploy script for recent Bikeshed boilerplate updates

---

convert-policy.py

Fixes #147
Policies not regenerated yet to avoid reintroducing paren bugs; will do that after #146 lands.

Remove "WHATWG" prefix from the <h2> version of the title

---

resources.whatwg.org/build/deploy.sh

We are not a 100% sure what exactly causes them to timeout as locally they always seem available around the same time, but hopefully this reduces the fail rate of PRs a bit.
Note that this does not address curl'ing of the deploy.sh script itself and also does not touch curl'ing the HTML checker as that code is likely to change anyway.
Fixes #117 (the remainder).

Retry most curl requests as they sometimes timeout

---

resources.whatwg.org/standard.css

As far as I know this only affects the HTML Standard.
This makes "MathML math" appear as "mathml math". And "Hidden state" as "hidden state", despite everywhere else using the former. The only somewhat intentional lowercase might be "Text", but we should just lowercase that in the source in that case.

Do not transform text in .category-list

---

convert-policy.py

This doesn't do anything due to a typo, but is also no longer needed as the titles are now consistent upstream (whatwg/sg).

Remove obsolete code from convert-policy.py

---

idea.whatwg.org/index.html
policy-template.html
spec.whatwg.org/index.html

* From policy pages, it was not possible to get back to /policies via the top bar
* From subdomains, it was not possible to get back to the homepage via the header
These were missed in 4d34512aeb618c8753e317b220a7937c2161fb11.

Small follow-up fixes to the redesign

---

convert-policy.py

It turns out lstrip does not do what I thought it did. Fixes the "orkstream Policy" title.
This bug was introduced in 4d34512aeb618c8753e317b220a7937c2161fb11. Thanks @michaelchampion for spotting!

Fix logic for computing the title of policies

---

whatwg.org/faq
whatwg.org/index.html
whatwg.org/irc

Hope I'm doing this right.
This is a direct copy of the IRC wiki page, but with one exception: I changed `irc://` to `ircs://` and added a colon before the `pre` block.
Ref #162

Move IRC wiki page to whatwg.org

---

whatwg.org/index.html

It turns out that the one reason we kept it for we didn't end up using it for.

Remove analytics

---

.gitignore
convert-policy.py
deploy.sh

Instead extract the mappings from sg/policy-link-mapping.txt directly.
Fixes #173.

Deduplicate whatwg.org deploy

---

.travis.yml
resources.whatwg.org/build/README.md
resources.whatwg.org/build/deploy.sh
resources.whatwg.org/build/review.sh

See #197 and https://github.com/whatwg/sg/issues/70.
This doesn't yet prevent re-building and deploying; discussions ongoing in #197.

WIP review draft deploy

---

resources.whatwg.org/standard.css

We accidentally broke it in https://github.com/tabatkins/bikeshed/commit/7a022f4ed5d215ee6aab86547be6126ba9c8135a, thinking the block added in #209 would suffice, but due to https://github.com/tabatkins/bikeshed/issues/1313 it does not work yet.
While waiting for https://github.com/tabatkins/bikeshed/issues/1313 to be fixed, include these styles, to un-break syntax highlighting.

Fix syntax highlighting for standards

---

resources.whatwg.org/spec.css
resources.whatwg.org/standard.css

The main purpose of this commit is to adapt to the new markup style in https://github.com/whatwg/html/pull/3768. This also fixes minor inconsistencies and redundancies noted throughout the stylesheet for pre elements. (Most notably, it will treat Bikeshed-produced IDL and CSS blocks the same as those in HTML.) And it removes special treatment of the "asn" class, which does not appear in any current specs.
/cc @Zirro @sideshowbarker.
We should merge this and https://github.com/whatwg/html/pull/3768 at roughly the same time.

Update syntax highlighting styles

---

resources.whatwg.org/standard-service-worker.js
resources.whatwg.org/website-service-worker.js

Before this, navigating to a page that gives a non-OK status for a living standard (e.g. https://streams.spec.whatwg.org/asdf) would cause the code to go down a path of trying to get the result from the cache. Since the cache would contain no entries for such pages, this would end up calling fetchEvent.respondWith(null). The result is a network error, giving a scary error page in various browers (e.g. "Corrupted Content Error" in Firefox).
After this page, the non-OK status only impacts the waitUntil() call, as intended.

Small fix to service worker error handling

---

resources.whatwg.org/build/deploy.sh

Closes #223.
This works best only after #225 is merged, as otherwise it loses warning information (because it only shows the output if the web service gave a non-200). Happy to rebase it afterward.
This reduces the number of HTTP requests by one in the happy case, since we don't need a dedicated warning/error check pass anymore. It also avoids the problem of #223 and only does one HTTP request in the unhappy case before bailing.

Output Bikeshed errors if they occur

---

.travis.yml

A recent update to the Python Markdown module broke our build, as the py-gfm module we use isn't compatible with markdown 3.x. This pins the versions of our Python modules to avoid such breakage.

Fix Markdown compilation deployment

---

resources.whatwg.org/standard-service-worker.js
resources.whatwg.org/standard-shared-with-dev.css
resources.whatwg.org/standard.css

In particular this adds the MDN margin annotation styles there. But it also deduplicates a lot of existing copy-and-pasted styles.
DO NOT MERGE until corresponding HTML and Bikeshed PRs have been merged. And then after that we need to kick of new builds of all the Bikeshed specs ASAP after merging.

Extract out styles that are shared with the HTML dev edition

---

resources.whatwg.org/standard-shared-with-dev.css

Follows https://github.com/whatwg/html/pull/4130. This style only applies to the dev edition, and should not be shared.

Remove one over-shared spec style

---

resources.whatwg.org/standard-service-worker.js

It seems we shouldn't ever be returning responses from older caches, though currently we sometimes do and this bit both @zcorpan and I. (We got an "opaque" CSS response that then got blocked.)
cc @jakearchibald

Restrict caches.match() by cacheKey

---

.gitignore
deploy.sh

See https://github.com/whatwg/sg/pull/79.

Code of Conduct is now maintained in Markdown upstream

---

whatwg.org/index.html
whatwg.org/validator/index.html

I found https://checker.html5.org/ is 502 now. I think it's the `validator`?

Fix HTML checker url

---

resources.whatwg.org/standard-new.css
resources.whatwg.org/standard.css
resources.whatwg.org/test-spec-new.html
resources.whatwg.org/test-spec.html

In particular, this uniformizes .domintro, .note, .warning, .example, .XXX, and .critical, in the following ways:
* Updates all of .domintro, .note, .warning, and .example to have the same style as the current .domintro for their decoration, with no tilt
* Updates all to the look the same for `<p class="thing">...</p>` and `<div class="thing"><p>...</p></div>`
* Updates all of them to have uniform padding and margin, so that e.g. the text aligns on the left, and the borders align on the left and right
* Improves the style for inline `<span>` versions of .note, .warning, and .XXX
* Removes the .big-issue synonym for .XXX
* Removes many redundant-in-practice rules that have accreted over time and serve only to create inconsistencies
* Makes it clearer what styles are shared, by explicitly …

Uniformize spec paragraph styles

---

resources.whatwg.org/build/deploy.sh

This change makes the deploy.sh script download the vnu.jar file from https://github.com/validator/validator/releases/download/jar/vnu.jar (rather than from https://sideshowbarker.net/nightlies/jar/vnu.jar).

Use GitHub URL for vnu.jar download

---

resources.whatwg.org/file-issue.js

This change:
* Requires the user to make a selection so we get a useful target node.
* Avoids running the script for each mouseup/keydown.
* Uses const/let throughout.

Modernize file-issue.js and make it run less

---

resources.whatwg.org/build/deploy.sh

This change makes the resources.whatwg.org/build/deploy.sh script download and use the (Linux) binary image of the HTML checker rather downloading and using the jar release of the checker and relying on using a system Java runtime to run that jar.

Use HTML checker binary image, not system Java

---

resources.whatwg.org/build/README.md
resources.whatwg.org/build/deploy.sh

This change causes the HTML checker to be invoked with the --filterfile argument if a file named `.htmlcheckerfilter` is found. The filter pattern (for suppressing particular messages from the checker) is then read from the specified file.
Otherwise, without this change, the HTML checker is instead invoked with the --filterpattern argument and the filer pattern is read directly from the CHECKER_FILTER environment variable. Testing in Travis CI indicates doing it that way doesn’t work as expected in some cases (due to shell escaping of the special characters and spaces in the pattern, or something.)

Use --filterfile for HTML checker

---

resources.whatwg.org/build/deploy.sh

This change causes the HTML checker to be invoked with the --verbose option. That causes the checker to emit the filename of every file it checks.
The advantages of using the --verbose option under CI are that:
* it ensures there will be continuous CI log output while the checker is running; and that in turns prevents us from ever hitting the case where the build reaches a no-log-output-for-more-than-N-minutes timeout (where for, e.g, Travis CI, the timeout is 10 minutes — and which we end up hitting in the case of the Encoding spec, where the checker is being run in CI on 66 files, and 30+ of those files are larger than 4MB each)
* it ensures that for anybody looking at (tailing) the CI log output, it won’t look like the build is hanging, when in fact it’s running the HTML checker (but …

Invoke the HTML checker with the --verbose option

---

resources.whatwg.org/standard-shared-with-dev.css
resources.whatwg.org/standard.css

And align offsets across right-positioned items. (0.3em doesn't make sense as the font-size isn't consistent across these boxes.)
Closes #281.

Improve tracking vector styling

---

.gitignore
deploy.sh
package.json
resources.whatwg.org/standard-shared-with-dev.css

Not sure when the Edge logo should be updated, now or after the stable release date, but in any case, here is the PR for it. 
See also: https://blogs.windows.com/windowsexperience/2019/11/04/introducing-the-new-microsoft-edge-and-bing/
---
| Old logo | New Logo |
|:---|:---|
| ![](https://raw.githubusercontent.com/alrra/browser-logos/bb23044804e7f78320241d582b71bed1576657d1/src/archive/edge_12-18/edge_12-18_512x512.png) | ![](https://raw.githubusercontent.com/alrra/browser-logos/bb23044804e7f78320241d582b71bed1576657d1/src/edge/edge_512x512.png)

Update Edge logo

---

deploy.sh

https://github.com/whatwg/whatwg.org/pull/285 added 103k files which
broke deploy on Travis due to exeeding the maximum log length.

Use `rsync --itemize-changes` to reduce log verbosity

---

whatwg.org/mailing-list

Everything that could be recovered from the Wayback Machine has been
restored, so there's no reason to link to it. The redirect mechanism
was never deployed.

Link to lists.whatwg.org from whatwg.org/mailing-list

---

convert-policy.py

Between 4d34512aeb618c8753e317b220a7937c2161fb11 and https://github.com/whatwg/sg/pull/77 this became obsolete I think.

Editorial: remove dead code from convert-policy.py

---

.travis.yml
convert-policy.py

This fixes a few subtle issues and is a prerequisite for fixing more.

Use CommonMark in convert-policy.py

---

.gitignore
convert-policy.py
deploy.sh

See https://github.com/whatwg/sg/pull/88. Needs to be merged afterwards. And also requires #295 and rebasing.

Working Mode is in Markdown now

---

resources.whatwg.org/biblio.json

This is the result of running
```python
#!/usr/bin/env python
import json
biblio = json.load(open("resources.whatwg.org/biblio.json", "r"))
string = json.dumps(biblio, ensure_ascii=False, allow_nan=False, sort_keys=True, indent=2) + "\n"
open("resources.whatwg.org/biblio.json", "w").write(string)
```
to help with #303 as far as output comparisons go.

Editorial: normalize biblio.json

---

convert-policy.py
site-template.html

For #303 I'd like to use this template for spec.whatwg.org and idea.whatwg.org.
This also adds some crossorigin="" attributes.

Make template suitable for other origins

---

.travis.yml

The default is now 3.6. The important thing here is to make it clear
that Python 3 is used in CI, since just `pip` and `python` are used
in scripts, which usually point to Python 2.

Specify the Python version to use on Travis (3.8)

---

resources.whatwg.org/build/deploy.sh

They will now use a title aligned with Review Drafts, use the snapshot logo, and generally include less data that is best looked for in the Living Standard.
Depends upon https://github.com/tabatkins/bikeshed/pull/1635.
Closes https://github.com/whatwg/meta/issues/88. Closes #309.

Improve Commit Snapshot setup

---

resources.whatwg.org/standard-shared-with-dev.css

This changes add CSS styles for the MDN annotations generated by Bikeshed. The change also removes the existing CSS styles we were using for the MDN annotations generated by Wattsi for the HTML standard.
(A separate change to the Wattsi sources will revise the element markup and attribute markup generated by Wattsi such that it matches what Bikeshed generates — allowing the CSS styles in this change to be be used/shared among the HTML standard and all other WHATWG standards.)

Change MDN-annotation styles to Bikeshed styles

---

resources.whatwg.org/standard.css

This avoids a .note italicizing it: https://github.com/whatwg/url/pull/495.

standard.css: pre { font-style: normal }

---

resources.whatwg.org/standard.css

This would make the warning in https://encoding.spec.whatwg.org/#dom-textdecoder-decode look a bit better (to me).

standard.css: code { font-style:normal }

---

resources.whatwg.org/standard.css

Needs to follow https://github.com/whatwg/html/pull/5549.

Remove HTML-specific dfn panel styles from standard.css

---

resources.whatwg.org/build/README.md
resources.whatwg.org/build/deploy.sh

Part of https://github.com/whatwg/meta/issues/173.

Enable specs to deploy using GitHub Actions

---

deploy.sh
package.json

The `Android WebView` was (is?) actually part of the Android Beta program, but now there is `Android WebView Beta`, so the `browser-logos` packages have been updated accordingly.
Ref: 
* https://play.google.com/store/apps/details?id=com.google.android.webview
* https://play.google.com/store/apps/details?id=com.google.android.webview.beta

Use `android-webview` instead of the `android-webview-beta` package

---

resources.whatwg.org/build/deploy.sh

https://github.com/shivanigithub/fetch/runs/776676042 failed of
attempting to deploy from a fork where the secrets aren't present.

Skip deploy step for forks of our spec repos

---

.github/workflows/build.yml

This is half of the solution, in addition the sg repository will need to
trigger the event:
https://developer.github.com/v3/repos/#create-a-repository-dispatch-event
Part of https://github.com/whatwg/sg/issues/110.

Add a repository_dispatch hook for whatwg/sg updates

---

.github/workflows/build.yml
deploy.sh

Also change the event name to be a bit more explicit, since the event
name shows up in the list of triggered actions and a longer name will be
easier to spot or search for:
https://github.com/whatwg/whatwg.org/actions

Actually deploy for the repository_dispatch event

---

resources.whatwg.org/standard-shared-with-dev.css

This change adds some additional CSS style adjustments related to MDN annos:
* one style adjustment that’s necessary due to the fact we’re sharing styles among both the HTML spec and WHATWG Bikeshed-generated specs.
* one style adjustment that’s necessary due to the fact the existing styles have "position: relative" for domintro boxes, as well as notes, warnings, and examples — so in cases where we have an element with an MDN anno inside of one of those, we need to move it to the right to get it out of containing block and back over to the right margin

Add stylesheet refinements for MDN annos

---

convert_policy.py

I guess running this twice is non-destructive, but it does not seem ideal. I only found out this is a thing that happens in Python because I was trying to have some code reuse over in whatwg/meta.

Do not run convert_policy.py when it is imported

---

resources.whatwg.org/standard.css

This change additionally modifies a few rules from Bikeshed's styles for integration with the dfn panels in the HTML spec.
See tabatkins/bikeshed#1772, which turns off Bikeshed's `style-dfn-panels` styles, and whatwg/html#5947, which modifies HTML's `html-dfn.js` script to work with these styles.

Add Bikeshed's style-dfn-panels styles to standard.css

---

whatwg.org/faq

Update the FAQ to account for AppCache removal from HTML

---

whatwg.org/style-guide

It has been colorspace in this document since the very beginning (7 November 2016), but on 9 May 2016 we changed colorspace to color space in the HTML Standard quite deliberately: https://github.com/whatwg/html/commit/c92fee202c1b4076209c127fc2151df1d2f68f98.
Recently this was discussed further in https://github.com/whatwg/html/pull/6562 and we decided to stick with color space.

Add space to color space

---

deploy.sh
resources.whatwg.org/build/deploy.sh

This reverts commit 7fa32e39833f777f5912790892b704399b9c308f.
https://github.com/validator/validator/releases/download/linux/vnu.linux.zip is working again now, and is the right URL to use.
https://github.com/validator/validator/releases/latest/download/vnu.linux.zip works, but it’s the URL for the most-recent stable release — which at this point is almost 1 year old.

Revert "build.sh: adjust HTML checker download location"

---

whatwg.org/chat

Followup to #366. I've added a custom domain so I can keep the links stable in case we move the logs to some other repo or service.

Use new domain for matrix logs

---

deploy.sh
resources.whatwg.org/build/deploy.sh

https://github.com/validator/validator/releases/download/latest/ now has all release artifacts (including the Linux, Windows, and macOS binaries).

Update vnu download URL in deploy.sh scripts

---

convert_sg_db.py

Otherwise we end up leaking Workstreams here, which is a little ugly.
Fixes #384.

Sort spec.whatwg.org by name of standard

---

resources.whatwg.org/build/deploy.sh

The "much greater/less than" unicode characters that look like list literals, I've made this mistake a few times... Lint would catch this early.
I don't think we need the "much greater/less than" characters in specs.

Add lint step for ambiguous list literals

---

images.whatwg.org/content-venn.svg
resources.whatwg.org/standard-shared-with-dev.css
resources.whatwg.org/standard.css
whatwg.org/style/specification
whatwg.org/style/subpages.css

Building on this [PR for the dev edition](https://github.com/whatwg/html/pull/7702), this PR updates some colours in the regular spec layout to help meet WCAG.
I have tried to find all instances of these colours in the repo to try and update them all (except for the mailing list entries and temporary files). 
This updates colour contrast of: 
* `orangered` on white, changing to #d5430c (sorry, I could not find named colour), improving contrast from `3.44 : 1` to `4.91 : 1`
* gray backgrounds in notes and MDN annotation from #EEE to #f5f5f5, consistent with [update in dev edition](https://github.com/whatwg/html/pull/7702), bumping contrast from `4.19 : 1` to `4.54 : 1` / `4.8 : 1` (MDN annotation)

Tweak colour contrast

---

resources.whatwg.org/standard-service-worker.js
resources.whatwg.org/standard.css

This makes declaring struct instances (in the sense of https://infra.spec.whatwg.org/#structs) much easier.
---
Extracted from https://github.com/whatwg/html/pull/6315. See some example usages at https://whatpr.org/html/6315/history.html#snapshotting-source-snapshot-params and https://whatpr.org/html/6315/history.html#navigate steps 14.7 and 14.13.6.

Add support for <dl class="props">

---

.github/workflows/build.yml

This generally keeps it in sync with whatwg/html, whatwg/spec-factory, and other places.

Meta: bump some build.yml numbers

---

.github/workflows/build.yml

As you can see in this log `@v3` issues a warning: https://github.com/whatwg/whatwg.org/actions/runs/3410148383/jobs/5672752326. Let's see if that warning disappears.

Meta: bump actions/setup-python

---

convert_sg_db.py

Other pages used hyperlinks to this one with anchors links. We want to fix the following page: https://wicg.github.io/admin/charter.html#liaisons which has links to this page, but it would be easier if the IDs were working, we believe that just inserting this id in the code will help a lot.
Co-authored-by: Guilherme Siquinelli <guiseek@gmail.com>

bugfix: generate section with id

---

resources.whatwg.org/standard.css

Although this is normally not necessary when they are adjacent to `<p>`s, sometimes they are adjacent to each other, in which case this is needed.
Showed up in https://github.com/whatwg/html/pull/8502.

Add a margin to <table>s

---

resources.whatwg.org/spec.css

On all spec pages, their logo doesn't have focus around the element.
This fails [WCAG 2.4.7 Focus Visible](https://www.w3.org/TR/WCAG21/#focus-visible)

Make focus visible on the logo element at the top of the page

---

resources.whatwg.org/commit-snapshot-shortcut-key.js

Fixing what I believe is a little bug in the `commit-snapshot-shortcut-key.js` script. In `html.spec.whatwg.org` it's loaded with the `async` flag, which means it can run after the `DOMContentLoaded` event has fired. The listener that sets up the keyboard shortcut will never run in that case. Only a script with `defer` is guaranteed to run before `DOMContentLoaded`.
The fix uses the `load` event instead, which is fired only after even the `async` scripts are finished running.
In the spec, [this is the place](https://html.spec.whatwg.org/#the-end:set-of-scripts-that-will-execute-as-soon-as-possible) where all the `async` scripts are flushed, and it runs between the `DOMContentLoaded` and `load` events.
I found this when trying to learn what exactly the difference between `async` and …

Recommend loading commit-snapshot-shortcut-key.js with defer as it installs a DOMContentLoaded listener

---

resources.whatwg.org/build/deploy.sh

This avoids generating review drafts for merge commits unless the merge  commit has modifications to the review draft (which I hope means that it's different from all parents of the merge).
The code prior to this change tries to generate a review draft if the  first parent of the merge commit introduces a review draft. (This happens if "git merge main" is done on a feature branch and main has introduced a review draft.)
This matches the change in 
https://github.com/whatwg/html-build/pull/284 .

Avoid generating review drafts for merge commits

---

resources.whatwg.org/build/deploy.sh

As of https://github.com/speced/bikeshed-boilerplate/commit/a569466c5c1f17da57f5ff47099b31f623491c1c it's on by default for all WHATWG specs

Remove now-unnecessary --die-on argument

---

resources.whatwg.org/standard-service-worker.js
resources.whatwg.org/standard-shared-with-dev.css
resources.whatwg.org/standard.css

Sorry, missed several specialized bits on the first pass, because I was just looking at DOM/etc, not HTML. Every single `color`, `background`, and `border` declaration in `standard.css` has been double-checked now.
* The `box-shadow` colors on the first-page nav blocks in HTML are kept as-is rather than being abstracted; once I swapped out the transparent overlay from nearly-white to nearly-black, the specified colors ended up still looking great, imo.
* I think that the "file a bug from selected text" functionality was removed, so possibly we can just kill that style.
* I also couldn't find any `tr.rare` elements, so I had to just guess at a reasonable color swap. I verified they looked reasonable on some random text, but I'm not sure if there's some particulars in context that would …

Darkmode the remaining colors used in a few HTML spots.

---

resources.whatwg.org/standard-shared-with-dev.css

SVGs are usually authored with a transparent background, and usually assume they're displayed against a light background, using black text/etc. This often renders them unreadable in darkmode.
To guard against this, this PR automatically gives them a white background, unless they have a `.darkmode-aware` class.
See also <https://github.com/whatwg/html/pull/10257>, where I'm fixing all of HTML's SVG's to be darkmode-aware. These PRs can be merged in either order; both "fix" the problem, this one just does it in a slightly less good (but more generic) way. I'll probably review the other WHATWG specs for SVG diagrams that need to be flagged as well, but later.

Defensively guard against non-darkmode-aware SVGs by giving them a white background.

---

.gitignore
whatwg.org/service-worker.js

The Invitation Policy, Privacy Policy, and Stages documents were not cached. Also sort these in the same order they are in .gitignore.

Update the service worker with new documents

---

whatwg.org/style-guide

See:
- https://english.stackexchange.com/a/241108/157224: for American english preferring `e.g.,`
- For preferring `i.e.,` over `i.e.`, that is just a matter of preference. The HTML Standard has 81 occurrences of `i.e., ` compared to 49 instances of `i.e. `
- https://github.com/whatwg/html/pull/10392#discussion_r1626822741
- https://github.com/whatwg/html/pull/10392#discussion_r1626825552

Specifically list `e.g.,` and `i.e.,` in the grammar section

---

resources.whatwg.org/tracking-vector.svg

See https://github.com/w3c/tr-design/issues/162#issuecomment-2122073793
Demo: https://software.hixie.ch/utilities/js/live-dom-viewer/saved/12744
This seems to work in Gecko and Chromium, but not WebKit.

Support dark mode in tracking-vector.svg
